---
title: "Menus TGV"
lang: fr
format: 
  html:
    theme: minty
    logo: images/Sncf_logo.png
    title-block-banner: true
    embed-resources: true
    toc: true
    toc-location: left
    toc-title: Au menu
    date: last-modified
    other-links:
      - text: SNCF Open Data
        href: https://ressources.data.sncf.com/explore/dataset/menus-des-bars-tgv/information/
css: styles.css
---

```{r}
#| label: donnees_packages
#| include: false

source("R/init.r")
```

## Boissons

```{r}
#| echo: false
tableau_categorie("Boissons")
```

## Sucré

```{r}
#| echo: false
tableau_categorie("Sucré")
```

## Salé

```{r}
#| echo: false
tableau_categorie("Salé")
```

## Apports caloriques moyens
```{r}
#| echo: false

tab_caracteristiques(carac = "Kcal_pour_100_ml_ou_100g", lab = "en Kcal pour 100ml ou 100g", tit = "Apports caloriques moyens", col = "#7993E6")
```

## Nutriments
### Protéïnes
```{r}
#| echo: false 
tab_caracteristiques(carac = "Protéines_100g_100ml_", lab = "en g pour 100ml ou 100g", tit = "Apports proteïniques moyens", col = "#A24545")
```

### Sucres
```{r}
#| echo: false
tab_caracteristiques(carac = "Glucides_100g_100ml_", lab = "en g pour 100ml ou 100g", tit = "Apports en sucres moyens", col = "#14A636")
```

## Prix
```{r}
#| echo: false
tab_caracteristiques(carac = "Prix_au_produit", lab = "en €", tit = "Prix", col = "#92A5A5")
```
